channels:
  - conda-forge

dependencies:
  - python=3.11.8                 # https://pyreadiness.org/3.11
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==28.5.1        # https://rpaframework.org/releasenotes.html
    - robocorp==2.0.1             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - requests==2.31.0            # https://pypi.org/project/requests
    - aiofiles==24.1.0
